version: '3.8'
services:
  redis:
    image: "redis"
    ports:
     - 6379:6379
  mongodb:
    image: "mongo"
    ports:
     - 27017:27017
    volumes:
     - /usr/local/var/mongodb:/data/db
     - /usr/local/var/log/mongodb:/data/logs

